# Telegram Bot Token
bot.token=8395844854:AAEMWJE6U1XHpp65QfkpfQ21hgQozY1R65c
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot
spring.datasource.username=bot_user
spring.datasource.password=TelegramBot123
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false